version: "3.8"

services:
  # MySQL Database for `account-service`
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    env_file:
      - ./account-service/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: account_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Account Service
  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: account-service-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - ./account-service/.env

volumes:
  mysql_data:
