version: "3.8"

services:
  # MySQL Database for `account-service`
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    env_file:
      - ./account-service/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: account_db
      MYSQL_USER: ${DB_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./account-service/init.sql:/docker-entrypoint-initdb.d/init.sql
  # Account Service
  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: account-service-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - ./account-service/.env

volumes:
  mysql_data:
